### ISSUE TITLE
After setting the font size to 1.5em, the size of the cursor is still 1.0em

### ISSUE THREAD

**Issue by flyisland** [satokaz/vscode-markdown-header-coloring#25]
I like the idea to change the color and size of headers in markdown, thanks!

After setting the font size to 1.5em or 2.0em, the size of the cursor is still 1.0em, which makes it very hard to use.

**Comment by satokaz** [comment]
@flyisland 

Please let me confirm that my recognition is correct.
If it is different, please tell me a little more specifically.

In such a sample, the cursor is recognized as the following image.
The cursor appears to follow the font-size.

```json
"markdown-header-coloring.textDecoration": "font-size: 2.0em; text-shadow: 2px 2px 3px rgba(0,0,0,0.5)",
"editor.cursorStyle": "block",
```

In both cases, the cursor is placed on header 2 (between e and a).

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/13635244/62076266-366b3900-b282-11e9-8c71-1bcea5977511.png">

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/13635244/62076332-631f5080-b282-11e9-8d64-53a6feb23c21.png">

**Comment by satokaz** [comment]
@flyisland 

I understand.
The previous post uses vscode insiders (1.37.0-insider 2019-07-29T05:27:38.167Z).

Are you using vscode stable (1.36.1)? 
The behavior is different from the stable version.
I did not care about that.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/13635244/62077423-03767480-b285-11e9-8246-184c0c93a09b.png">

Is the expected behavior with vscode insiders?

**Comment by flyisland** [comment]
@satokaz yes, I'm using the stable version 1.36.1.

After setting the fontsize to 1.5em ...

![image](https://user-images.githubusercontent.com/547085/62099356-4d308080-b2c0-11e9-806f-d1dd98393f77.png)

As you can see, the "col" is 8 in the status bar, but the cursor is placed between C and D of "# ABCDE", which is 6. 

![image](https://user-images.githubusercontent.com/547085/62098854-bfa06100-b2be-11e9-9e16-d03d7ca247c4.png)

**Comment by satokaz** [comment]
@flyisland 

sorry, I can't figure out how to do it correctly with vscode stable...

However, I think that vscode insiders will be the expected behavior.
Wait for the vscode stable 1.37 release.

image below shows the behavior with vscode insiders: 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/13635244/62181030-e1681980-b38c-11e9-9ceb-ea2840e6c533.png">

**Comment by flyisland** [comment]
got it, thanks @satokaz

**Comment by satokaz** [comment]
@flyisland 

vscode 1.37 has been released.
However, the behavior was not improved.
Sorry for the expectation.

I will investigate...

**Comment by flyisland** [comment]
got it, thanks for the update!

**Comment by satokaz** [comment]
@flyisland 

I found workaround.
Set the following settings in settings.json.

```
    "editor.fontLigatures": true
```

**Comment by flyisland** [comment]
@satokaz thanks very much, it does work!
